### ISSUE TITLE
Add support to control config using `config -> runtime.exs` instead of adding it in `application.ex`

### ISSUE THREAD

**Issue by shivamsupr** [ryanwinchester/slack_elixir#4]
Currently, we have to add the config using `application.ex` which seems a bit old school. Can we have a way to add this using `config -> runtime.exs`?

**Comment by ryanwinchester** [comment]
I could add instruction on how to do it to readme but it should work like this with runtime config.
The comment in the example code in the readme was suggesting this. I didn't spend enough time
on the readme.

```elixir
  def start(_type, _args) do
    children = [
      # ...
      {Slack.Supervisor, Application.get_env(:my_app, MyApp.SlackBot)}
    ]

    opts = [strategy: :one_for_one, name: MyApp.Supervisor]
    Supervisor.start_link(children, opts)
  end
```

```elixir
# config/runtime.exs

config :my_app, MyApp.SlackBot,
  app_token: "MY_SLACK_APP_TOKEN",
  bot_token: "MY_SLACK_BOT_TOKEN",
  bot: MyApp.SlackBot
```

**Comment by ryanwinchester** [comment]
Updated README in 8562533

**Comment by mustela** [comment]
Hey there, is this really working for you guys? If we move configs to the runtime file, the supervisor is starting without the config details and failing to load

```
* (Mix) Could not start application avance: Avance.Application.start(:normal, []) returned an error: shutdown: failed to start child: Slack.Supervisor
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Keyword.pop!/2
            (elixir 1.15.7) lib/keyword.ex:1315: Keyword.pop!(nil, :app_token)
            (slack_elixir 1.1.0) lib/slack/supervisor.ex:20: Slack.Supervisor.init/1
            (stdlib 5.1.1) supervisor.erl:330: :supervisor.init/1
            (stdlib 5.1.1) gen_server.erl:962: :gen_server.init_it/2
            (stdlib 5.1.1) gen_server.erl:917: :gen_server.init_it/6
            (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by ryanwinchester** [comment]
What do your config and Application.start look like?

**Comment by mustela** [comment]
@ryanwinchester forget about it, my mistake, I was initialising it incorrectly.
